name: smart_delivery_gabon_full_app

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  http: ^1.1.0

  # ----------- SUPABASE UNIQUEMENT -----------
  supabase_flutter: ^2.10.3
  # ------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/smart_delivery_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

